### ISSUE TITLE
java.util.NoSuchElementException on Kafka message over 74 characters

### ISSUE THREAD

**Issue by simno** [tresata/spark-kafka#2]
If a message in a kafka topic is 74 or more characters then the following error occurs:

```
java.util.NoSuchElementException
    at kafka.utils.IteratorTemplate.next(IteratorTemplate.scala:39)
    at com.tresata.spark.kafka.KafkaRDD$$anon$1.next(KafkaRDD.scala:229)
    at com.tresata.spark.kafka.KafkaRDD$$anon$1.next(KafkaRDD.scala:220)
    at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:389)
    at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
    at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
    at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
    at scala.collection.AbstractIterator.to(Iterator.scala:1157)
    at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
    at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
    at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
    at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
    at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:905)
    at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$12.apply(RDD.scala:905)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1848)
    at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1848)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:88)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

You can reproduce this error by modifying the tests as follows:

```
  describe("KafkaRDD") {
    it("should post messages to kafka") {
      val topic = "topic1"
      createTopic(topic)

      val rdd = sc.parallelize(List(("1", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), ("2", "b")))
      KafkaRDD.writeWithKeysToKafka(rdd, topic, new ProducerConfig(getProducerConfig(brokerConf.hostName + ":" + brokerConf.port)))
      Thread.sleep(1000)
    }

    it("should collect the correct messages without provided offsets") {
      val topic = "topic1"

      val rdd = KafkaRDD(sc, topic, OffsetRequest.EarliestTime, OffsetRequest.LatestTime, SimpleConsumerConfig(getConsumerConfig(brokerPort)))
      assert(rdd.collect.map(pomToTuple).toList ===
      List((0, 0L, "1", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"), (0, 1L, "2", "b"), (0, 2L, null, "b"), (0, 3L, null, "c"), (0, 4L, null, "c"), (0, 5L, null, "c")))
      assert(rdd.stopOffsets === Map(0 -> 6L))
   }

}
```

**Comment by koertkuipers** [comment]
yikes
could this be a bug in kafka itself? seems the error is happening in the iterator of kafka's FetchRequest

**Comment by cfusi** [comment]
Hi,
I reproduced the symptom. It's not a real problem.
The error occurs in the tests only. It depends on the setting of the property:
fetch.message.max.bytes=100
in the KafkaRDDSpec.functiongetConsumerConfig.
Comment it (so to get the default 1024 \* 1024), or raise it to a bigger value and retry
